POST http://localhost:80/start

###

POST http://localhost:80/restart

###

GET http://localhost:80/players

###

GET http://localhost:80/teams
 
###

POST http://localhost:80/bid
Content-Type: application/json

{
  "player": "Trond",
  "bid": ["Spades", "Ace"]
}

###

POST http://localhost:80/bid
Content-Type: application/json

{
  "player": "Kari",
  "bid": ["Clubs", "Jack"]
}

###

POST http://localhost:80/bid
Content-Type: application/json

{
  "player": "Per",
  "bid": ["Diamonds", 10]
}

###

POST http://localhost:80/bid
Content-Type: application/json

{
  "player": "Kai Åge",
  "bid": ["Hearts", 6]
}

###

POST http://localhost:80/addplayer
Content-Type: application/json

{
  "name": "Trond"
}

###

POST http://localhost:80/addplayer
Content-Type: application/json

{
  "name": "Per"
}

###

POST http://localhost:80/addplayer
Content-Type: application/json

{
  "name": "Kari"
}

###

POST http://localhost:80/addplayer
Content-Type: application/json

{
  "name": "Kai Åge"
}